CREATE TABLE Designacion (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  edicion_id INTEGER NOT NULL,
  persona_id INTEGER NOT NULL,
  activo INTEGER DEFAULT 1,
  FOREIGN KEY(edicion_id) REFERENCES Edicion(id) ON DELETE CASCADE,
  FOREIGN KEY(persona_id) REFERENCES Persona(id) ON DELETE CASCADE
);