-- Migración 9: Estadísticas de jugador por partido (nivel medio, ~25 métricas)

CREATE TABLE IF NOT EXISTS EstadisticaPartidoJugador (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  partido_id INTEGER NOT NULL,
  persona_id INTEGER NOT NULL,
  equipo_id INTEGER NOT NULL,
  minutos_jugados INTEGER DEFAULT 0,
  goles INTEGER DEFAULT 0,
  asistencias INTEGER DEFAULT 0,
  tiros INTEGER DEFAULT 0,
  tiros_puerta INTEGER DEFAULT 0,
  pases_totales INTEGER DEFAULT 0,
  pases_precisos INTEGER DEFAULT 0,
  pases_clave INTEGER DEFAULT 0,
  centros_totales INTEGER DEFAULT 0,
  centros_buenos INTEGER DEFAULT 0,
  entradas INTEGER DEFAULT 0,
  intercepciones INTEGER DEFAULT 0,
  recuperaciones INTEGER DEFAULT 0,
  despejes INTEGER DEFAULT 0,
  duelos_ganados INTEGER DEFAULT 0,
  duelos_perdidos INTEGER DEFAULT 0,
  faltas_cometidas INTEGER DEFAULT 0,
  faltas_recibidas INTEGER DEFAULT 0,
  tarjetas_amarillas INTEGER DEFAULT 0,
  tarjetas_rojas INTEGER DEFAULT 0,
  penaltis_marcados INTEGER DEFAULT 0,
  penaltis_fallados INTEGER DEFAULT 0,
  dobles_penaltis_marcados INTEGER DEFAULT 0,
  dobles_penaltis_fallados INTEGER DEFAULT 0,
  paradas INTEGER DEFAULT 0,
  saques_banda INTEGER DEFAULT 0,
  rating REAL DEFAULT 0,
  FOREIGN KEY(partido_id) REFERENCES Partido(id) ON DELETE CASCADE,
  FOREIGN KEY(persona_id) REFERENCES Persona(id),
  FOREIGN KEY(equipo_id) REFERENCES Equipo(id)
);
